### ISSUE TITLE
Fix javadoc errors in build

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/WorldWindJava#16]
The build output is littered with 200 javadoc warnings and errors. For instance,

```text
 error: self-closing element not allowed
 * <p/>

error: block element not allowed within inline element <code>: pre
 * <pre>

warning: empty <p> tag
 * <p/> <p>blah blah blah:</p>
```

The javadoc text should be edited to eliminate this noisy output from the build.

**Comment by wcmatthysen** [comment]
I can help with this. The javadoc parser in Java 8 produces more strict HTML. It is just a matter of going through the comments and editing it to pass the requirements of the parser.

**Comment by emxsys** [comment]
@wcmatthysen Thanks. But, I hope you haven't started yet. I'm in the middle of making the changes now. :)

**Comment by wcmatthysen** [comment]
Nope, I haven't started with it. It looks like a lot of small changes scattered throughout the code. Mostly self-closing paragraph fixes from what I saw in the error log.
