### ISSUE TITLE
Remove Jackson sources

### ISSUE THREAD

**Issue by wcmatthysen** [WorldWindEarth/WorldWindJava#22]
The embedded Jackson sources should be removed and we should instead add the Jackson jar as an external dependency. See this pull request of mine for some details: https://github.com/NASAWorldWind/WorldWindJava/pull/14

**Comment by wcmatthysen** [comment]
@emxsys, I don't think the way WorldWind has always embedded the Jackson sources is the right way of doing things. Jackson is an external dependency and should be handled as such. I proposed the change in a very old pull-request, but it was never considered. As far as I can tell WorldWind depended on version 1 of the library. I can add Jackson 1.9.13 (which is the latest version 1 build) as an external jar that we build against. I can name it jackson-core-asl.jar (omitting the version number as we do with JOGL and Gluegen). We can maybe consider to upgrade to the latest version 2 branch of Jackson in the future (as listed here: https://github.com/FasterXML/jackson).

**Comment by emxsys** [comment]
Closed with pull request #23 from @wcmatthysen
