### ISSUE TITLE
Perform continuous integration with multiple versions of Java

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/WorldWindJava#27]
Consider modifying the `.travis.yml` to test the WorldWindJava build with multiple versions of Java, for instance:

- openjdk8
- oraclejdk8
- oraclejdk9
- oraclejdk11

See: https://docs.travis-ci.com/user/languages/java/#testing-against-multiple-jdks

**Comment by emxsys** [comment]
In progress in the enhance/travis branch

**Comment by emxsys** [comment]
Gleaned from https://www.deps.co/guides/travis-ci-latest-java/
> JDK’s are downloaded from jdk.java.net. You can use `oraclejdkN` or `openjdN` where N is the JDK version number, e.g. `oraclejdk10` or `openjdk8`. You can also run tests against the latest early access builds using `oraclejdk-ea` and `openjdk-ea`. The JDK’s are downloaded by the [`install-jdk.sh`](https://github.com/sormuras/bach#install-jdksh) script.
>
> The full list of available JDKs is:
>
> - oraclejdk7
> - oraclejdk8
> - oraclejdk9
> - oraclejdk10
> - oraclejdk11
> - openjdk7
> - openjdk8
> - openjdk9
> - openjdk10
> - openjdk11
> - openjdk-ea
> 
> Testing against this many JDK’s is probably wasteful of Travis CI’s resources. For most projects there are no differences between Oracle’s JDK and OpenJDK. We would recommend picking either Oracle’s JDK or OpenJDK to run tests against all of the versions. With the other JDK you probably only need to test the current long term support release, feature release, and early access release.

**Comment by emxsys** [comment]
@wcmatthysen FYI:
- I added a test build with an early access OpenJDK (configured with _failures allowed_), and it did fail. See: https://travis-ci.com/WorldWindEarth/WorldWindJava/builds/108347677
- Next steps: With multiple JDKs, I need to ensure the deploy actions only occur with just one JDK.

**Comment by wcmatthysen** [comment]
@emxsys, looks great. From what I can see in the logs, it looks like some OpenGL issue that is failing the openjdk-ea build:

    [junit] Testsuite: gov.nasa.worldwind.util.OGLUtilTest
    [junit] Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.157 sec
    [junit] 
    [junit] Testcase: testPngFile(gov.nasa.worldwind.util.OGLUtilTest):	Caused an ERROR
    [junit] /tmp/jogamp_0000/file_cache/jln6310997194525872984/jln6167345031823347284/natives/linux-amd64/libnativewindow_awt.so: /home/travis/openjdk-ea/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /tmp/jogamp_0000/file_cache/jln6310997194525872984/jln6167345031823347284/natives/linux-amd64/libnativewindow_awt.so)
    [junit] java.lang.UnsatisfiedLinkError: /tmp/jogamp_0000/file_cache/jln6310997194525872984/jln6167345031823347284/natives/linux-amd64/libnativewindow_awt.so: /home/travis/openjdk-ea/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /tmp/jogamp_0000/file_cache/jln6310997194525872984/jln6167345031823347284/natives/linux-amd64/libnativewindow_awt.so)
    [junit] 	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
    [junit] 	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
    [junit] 	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
    [junit] 	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
    [junit] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
    [junit] 	at java.base/java.lang.Runtime.load0(Runtime.java:765)
    [junit] 	at java.base/java.lang.System.load(System.java:1866)
    [junit] 	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:603)
    [junit] 	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
    [junit] 	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
    [junit] 	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
    [junit] 	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
    [junit] 	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
    [junit] 	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
    [junit] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
    [junit] 	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
    [junit] 	at jogamp.nativewindow.jawt.JAWTUtil.<clinit>(JAWTUtil.java:336)
    [junit] 	at java.base/java.lang.Class.forName0(Native Method)
    [junit] 	at java.base/java.lang.Class.forName(Class.java:417)
    [junit] 	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:344)
    [junit] 	at com.jogamp.nativewindow.NativeWindowFactory$3.run(NativeWindowFactory.java:340)
    [junit] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
    [junit] 	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:340)
    [junit] 	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1721)
    [junit] 	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
    [junit] 	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
    [junit] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
    [junit] 	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
    [junit] 	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
    [junit] 	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1021)
    [junit] 	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
    [junit] 	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
    [junit] 	at gov.nasa.worldwind.Configuration.getMaxCompatibleGLProfile(Configuration.java:662)
    [junit] 	at gov.nasa.worldwind.util.OGLUtilTest.setUp(OGLUtilTest.java:34)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 
    [junit] 
    [junit] Testcase: testPngStream(gov.nasa.worldwind.util.OGLUtilTest):	Caused an ERROR
    [junit] No default device available
    [junit] com.jogamp.opengl.GLException: No default device available
    [junit] 	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2300)
    [junit] 	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1021)
    [junit] 	at com.jogamp.opengl.GLProfile.get(GLProfile.java:1050)
    [junit] 	at com.jogamp.opengl.GLProfile.getMaxFixedFunc(GLProfile.java:803)
    [junit] 	at gov.nasa.worldwind.Configuration.getMaxCompatibleGLProfile(Configuration.java:662)
    [junit] 	at gov.nasa.worldwind.util.OGLUtilTest.setUp(OGLUtilTest.java:34)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
