### ISSUE TITLE
Cleanup tags 

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/WorldWindJava#31]
There's an errant tag in the repo that is cluttering the [releases](https://github.com/WorldWindEarth/WorldWindJava/releases): daily/20170112 (b81455c).  This tag has no value. I propose we delete this tag.

**Comment by wcmatthysen** [comment]
@emxsys, I agree. We should only keep valid tags.

**Comment by wcmatthysen** [comment]
Removed the tag. You can clean up your local repository with this command:

    git fetch --prune origin +refs/tags/*:refs/tags/*
