### ISSUE TITLE
Publish artifacts to Maven central

### ISSUE THREAD

**Issue by wcmatthysen** [WorldWindEarth/WorldWindJava#36]
We need to get the WorldWind jars published on Maven central so that developers can easily include it in their projects. One of the forks that are doing this that we can reference for help or get help from is: https://github.com/pcmehlitz/WorldWindJava-pcm  (Peter C Mehlitz's fork)

**Comment by emxsys** [comment]
What group ID should we use?
- `earth.worldwind`?

**Comment by wcmatthysen** [comment]
Yes, I think that will work nicely.

**Comment by wcmatthysen** [comment]
@emxsys, I think we should get a bintray account up and running. We can then auto-publish snapshot builds of the develop branch with Travis, every time a pull-request is merged in. Releases can then be published every time we merge develop into master. Or, how do you think we should handle releases?

**Comment by wcmatthysen** [comment]
@emxsys, I've managed to get the maven artifact publishing to work (the changes are in #49). Whenever we merge a pull-request into the `develop` branch a snapshot version will be built and published to the JFrog OSS artifactory repository at:

    https://oss.jfrog.org/artifactory/oss-snapshot-local/earth/worldwind/worldwind/

The current snapshot-version is 2.2.0-SNAPSHOT.

When we want to release a version we need to merge into master and tag the branch (probably with the release number). This will cause a release version to be built and published to bintray at:

   https://bintray.com/beta/#/worldwindearth/maven/WorldWindJava

I can merge the pull-request into `develop`. This will cause a snapshot to be built. We will then just need to publish instructions on how to get the latest snapshot versions via maven in the readme file somewhere.

**Comment by wcmatthysen** [comment]
I've merged pull-request #49 into `develop` and it successfully published the snapshots. We now have snapshots available on the JFrog OSS artifactory repository that can be pulled in as dependencies for other applications. I have done separate tests and the publishing of the release jars to bintray work as well. We just need to update the readme file with additional information on how to pull in the snapshots and releases at some stage. I think that should happen when we decide to actually perform a 2.2.0 release. I think this issue can be closed for now.

**Comment by jrepko** [comment]
Is there reason why the worldwindx jar isn't publishing or is it just a mistake?   I'm looking at updating Glimpse to use JOGL 2.3.x but then I need to also update its worldwind dependencies.

**Comment by wcmatthysen** [comment]
@jrepko, I looked at the WorldWindAndroid `build.gradle` files as a guideline when I created the Gradle build script for WorldWindJava. In the WorldWindAndroid build scripts they do not publish the worldwindx jar. The reasoning is that the worldwindx jar is supposed to only contain the example applications and isn't something that you would normally need to depend on when you create an application.

**Comment by jrepko** [comment]
Makes sense.  The glimpse library has at least one example that depends on it, but I don't see why it couldn't be rewritten.

**Comment by wcmatthysen** [comment]
If there is some class you depend on in the worldwindx package for your library, we could move it into the core worldwind package. Just open an issue for it and we can have a discussion surrounding it.

**Comment by jrepko** [comment]
Thanks. I'll look into it more and do that if it makes sense.
