### ISSUE TITLE
SurfaceText has no rotation support

### ISSUE THREAD

**Issue by Sufaev** [WorldWindEarth/WorldWindJava#37]
Sometimes it is required to put SurfaceText rotated according North.
This possibility is absent but easy to add.

1) Add angle attribute, its setter and getter to SurfaceText class.
2) Add glRotated method call into applyDrawTransform.

See example of overridden class:
```
public class CustomSurfaceText extends SurfaceText {

    private double angle;

    public CustomSurfaceText(String text, Position position) {
        super(text, position);
    }

    public CustomSurfaceText(String text, Position position, Font font, Color color) {
        super(text, position, font, color);
    }

    public double getAngle() {
        return angle;
    }

    public void setAngle(double angle) {
        this.angle = angle;
    }

    @Override
    protected void applyDrawTransform(DrawContext dc, SurfaceTileDrawContext sdc) {
        super.applyDrawTransform(dc, sdc);
        dc.getGL().getGL2().glRotated(-angle, 0, 0, 1);
    }
}
```

**Comment by wcmatthysen** [comment]
Hi @Sufaev, thanks for picking that up. Could you add this code to the `SurfaceText` class itself, and create a pull-request so that we can get this in the code-base?

**Comment by Sufaev** [comment]
Hi @wcmatthysen.
I am discussing with @emxsys now if I should fork all repos to add PRs to all bug fixes, or may be he give me rights to create branches with fixes in main repos.
When I clarify this, I will definetly commit this improvement.

**Comment by wcmatthysen** [comment]
Cool, let me know. I would like to get your fixes and improvements in. Especially the MercatorTiledImageLayer refactor as that looks like a useful improvement.

**Comment by Sufaev** [comment]
I have created pull request.
The only thing - I found issue with text truncation during testing.
Could you test it also using SurfaceTextUsage app?
