### ISSUE TITLE
Tilting Globe no longer possible

### ISSUE THREAD

**Issue by lucgirardin** [WorldWindEarth/WorldWindJava#51]
### Description
Up to at least version 2.0.0-986, it was possible to tilt the plane in Flat mode. This is no longer possible with the latest version of WorldWindJava.

**Expected behavior:** 
The view should tilt and provide some kind of 2.5D view.

**Actual behavior:** 
No effect.

### Steps to Reproduce
1. Run the demo
2. Switch to Globe -> Flat
3. Try to tilt using Shift-Mouse-Up/Down or using the buttons

**Reproduces how often:** 
Always

### Operating System and Version 
Windows, macOS, and Linux using version 2.2.0

### Additional Information
There was a similar report posted in the WorldWind Forum:
https://forum.worldwindcentral.com/forum/world-wind-java-forums/development-help/156698-world-wind-java-2-1-0-earthflat-no-longer-allows-tilt

I am happy to investigate more, but it would be very useful to get any information on what may have triggered this change of behavior, i.e. was this intentional, a side effect of a change, or a raw bug?

**Comment by wcmatthysen** [comment]
Hi @lucgirardin. It might have been a bug that slipped in that broke the flat-mode tilting. You could check what commits occurred after version 2.0.0-986 that are related to `EarthFlat` and `BasicOrbitView`. Maybe `BasicOrbitView` doesn't work properly and some changes from the now-deprecated `FlatOrbitView` should be incorporated into `BasicOrbitView` to allow the flat-mode tilting to work with `EarthFlat`.

**Comment by wcmatthysen** [comment]
Fixed in PR #52.

**Comment by lucgirardin** [comment]
Thanks Wiehann, all good :-)
