### ISSUE TITLE
Update IntelliJ IDE settings for community edition

### ISSUE THREAD

**Issue by emxsys** [WorldWindEarth/WorldWindJava#6]
Update the JetBrains IntelliJ settings to reflect the community edition of WorldWindJava.  Use the IntelliJ Community Edition for the settings.

**Comment by emxsys** [comment]
In progress. Working with [IntelliJ Community Edition 2019.1](https://www.jetbrains.com/idea/).

**Comment by emxsys** [comment]
@wcmatthysen Just curious, what IDE are you using?

**Comment by wcmatthysen** [comment]
I'm using NetBeans.

**Comment by emxsys** [comment]
NetBeans is my first choice too.
