### ISSUE TITLE
MGRS conversion fixes

### ISSUE THREAD

**Issue by wcmatthysen** [WorldWindEarth/WorldWindJava#67]
Pull in fixes for MGRS coordinate conversion from upstream PR [#157](https://github.com/NASAWorldWind/WorldWindJava/pull/157) of @gbburkhardt. The corresponding description from the PR is:

> Fix two problems:
> 
> a) Index out of bounds error due to typo in convertMGRSToUPS; clearly the index should have been 1 instead of 12.
> b) Conversions from geodetic to MGRS would fail for low southern latitudes (zone 0). Geotrans 3.7 has this problem fixed. The WorldWind conversion code was derived from NGA's Geotrans. Test case:
> Lat: -89.345400 deg, Lon: -48.930600 deg ==> MGRS: AZN 45208 47747

See issue [#160](https://github.com/NASAWorldWind/WorldWindJava/issues/160) in upstream repository as well.

**Comment by Sufaev** [comment]
Bu the way, I have ported this conversions earlier to Android code base.
So I probably need to copy this fixes to Android branch too.
Will wait the result.

**Comment by wcmatthysen** [comment]
OK, the fix for this was done in PR #72. I'll take a look at porting the fixes to the Android code-base before closing this issue.

**Comment by PJHogan** [comment]
You guys are AMAZING!  Nice work!

**Comment by wcmatthysen** [comment]
The fixes are now ported to the Android code-base. So, I guess we can close this issue.
